name: Build Artifacts

on: pull_request

jobs:
  build_artifacts:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "$JAVA_HOME_8_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Build with Gradle
        run: ./gradlew build
